### PR TITLE
Merge Sort || C++|| O(nlogn)

### PR DESCRIPTION
**Pull request by akshaygidwani404**
A well commented merge sort code in C++
Time complexity: O(nlogn)

### CODE REVIEW

**Comment by heyimShivam** [comment]
please remove comments

**Comment by akshaygidwani404** [comment]
Okay

**Comment by akshaygidwani404** [comment]
Hi @heyimShivam! I have updated the code by removing the comments. Please do review and merge it. Thanks.

**Comment by heyimShivam** [comment]
done

**Pull request merged**
